/* Generated by Yosys 0.61+21 (git sha1 967b47d98, clang++ 18.1.3 -fPIC -O3) */

module \$paramod\baud_gen\CLKS_PER_BIT=s32'00000000000000000000001000101011 (clk, rst_n, baud_tick);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  output baud_tick;
  wire baud_tick;
  wire [9:0] _0_;
  wire [31:0] _1_;
  reg [9:0] clk_cnt;
  assign _1_ = clk_cnt + 32'd1;
  assign baud_tick = clk_cnt == 10'h22a;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) clk_cnt <= 10'h000;
    else clk_cnt <= _0_;
  assign _0_ = baud_tick ? 10'h000 : _1_[9:0];
endmodule

module tqvp_zul_uart(clk, rst_n, ui_in, uo_out, address, data_in, data_write_n, data_read_n, data_out, data_ready, user_interrupt);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [7:0] ui_in;
  wire [7:0] ui_in;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  input [5:0] address;
  wire [5:0] address;
  input [31:0] data_in;
  wire [31:0] data_in;
  input [1:0] data_write_n;
  wire [1:0] data_write_n;
  input [1:0] data_read_n;
  wire [1:0] data_read_n;
  output [31:0] data_out;
  wire [31:0] data_out;
  output data_ready;
  wire data_ready;
  output user_interrupt;
  wire user_interrupt;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire [31:0] _10_;
  wire _unused;
  wire baud_tick;
  reg interrupt_reg;
  wire [7:0] rx_data;
  wire rx_data_valid;
  wire tx_busy;
  reg tx_valid_reg;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) interrupt_reg <= 1'h0;
    else if (_02_) interrupt_reg <= _00_;
  assign _02_ = | { _06_, rx_data_valid };
  assign _03_ = ! address;
  assign _04_ = address == 6'h04;
  assign _05_ = _03_ && _07_;
  assign _06_ = _04_ && _08_;
  assign _07_ = data_write_n != 2'h3;
  assign _08_ = data_read_n != 2'h3;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tx_valid_reg <= 1'h0;
    else tx_valid_reg <= _01_;
  assign _01_ = _05_ ? 1'h1 : 1'h0;
  assign _09_ = _06_ ? 1'h0 : 1'hx;
  assign _00_ = rx_data_valid ? 1'h1 : _09_;
  assign data_out = _03_ ? { 31'h00000000, tx_busy } : _10_;
  assign _10_ = _04_ ? { 24'h000000, rx_data } : 32'd0;
  \$paramod\baud_gen\CLKS_PER_BIT=s32'00000000000000000000001000101011  i_baud_gen (
    .baud_tick(baud_tick),
    .clk(clk),
    .rst_n(rst_n)
  );
  uart_rx i_uart_rx (
    .baud_tick(baud_tick),
    .clk(clk),
    .data_out(rx_data),
    .data_valid(rx_data_valid),
    .rst_n(rst_n),
    .rx_pin(ui_in[7])
  );
  uart_tx i_uart_tx (
    .baud_tick(baud_tick),
    .busy(tx_busy),
    .clk(clk),
    .data_in(data_in[7:0]),
    .data_valid(tx_valid_reg),
    .rst_n(rst_n),
    .tx_pin(uo_out[0])
  );
  assign _unused = 1'h0;
  assign data_ready = 1'h1;
  assign user_interrupt = interrupt_reg;
endmodule

module uart_rx(clk, rst_n, baud_tick, rx_pin, data_out, data_valid);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input baud_tick;
  wire baud_tick;
  input rx_pin;
  wire rx_pin;
  output [7:0] data_out;
  reg [7:0] data_out;
  output data_valid;
  reg data_valid;
  wire [7:0] _00_;
  wire [31:0] _01_;
  wire [7:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire [3:0] _16_;
  wire [7:0] _17_;
  wire [7:0] _18_;
  wire _19_;
  wire [1:0] _20_;
  wire _21_;
  wire [1:0] _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire [2:0] _26_;
  wire [2:0] _27_;
  wire [1:0] _28_;
  wire [1:0] _29_;
  wire [7:0] _30_;
  wire [7:0] _31_;
  reg [2:0] bit_idx;
  reg rx_sync;
  reg [7:0] shift_reg;
  reg [1:0] state;
  assign _01_ = bit_idx + 32'd1;
  assign _02_ = shift_reg & _17_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state <= 2'h0;
    else if (_09_) state <= _28_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_out <= 8'h00;
    else if (_10_) data_out <= shift_reg;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) bit_idx <= 3'h0;
    else if (_11_) bit_idx <= _27_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_valid <= 1'h0;
    else if (_12_) data_valid <= _24_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) shift_reg <= 8'h00;
    else if (_13_) shift_reg <= _00_;
  assign _03_ = { _23_, rx_sync } != 2'h3;
  assign _04_ = { _19_, _15_ } != 2'h3;
  assign _05_ = | { _25_, _23_, _21_, _19_ };
  assign _06_ = | { _23_, _19_ };
  assign _07_ = | { _25_, _23_ };
  assign _08_ = ~ _14_;
  assign _09_ = & { baud_tick, _03_, _04_, _05_ };
  assign _10_ = & { _25_, baud_tick };
  assign _11_ = & { baud_tick, _06_ };
  assign _12_ = & { baud_tick, _07_ };
  assign _13_ = & { baud_tick, _08_ };
  assign _14_ = | { _25_, _23_, _21_ };
  assign _15_ = bit_idx < 32'd7;
  assign _16_ = - $signed({ 1'h0, bit_idx });
  assign _17_ = ~ _30_;
  assign _18_ = _02_ | _31_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rx_sync <= 1'h1;
    else rx_sync <= rx_pin;
  assign _19_ = state == 2'h2;
  assign _20_ = rx_sync ? 2'h0 : 2'h2;
  assign _21_ = state == 2'h1;
  assign _22_ = rx_sync ? 2'hx : 2'h1;
  function [0:0] _60_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _60_ = b[0:0];
      2'b1?:
        _60_ = b[1:1];
      default:
        _60_ = a;
    endcase
  endfunction
  assign _24_ = _60_(1'hx, 2'h1, { _23_, _25_ });
  assign _23_ = ! state;
  assign _25_ = state == 2'h3;
  assign _00_ = _19_ ? _18_ : 8'hxx;
  assign _26_ = _15_ ? _01_[2:0] : 3'h0;
  function [2:0] _65_;
    input [2:0] a;
    input [5:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _65_ = b[2:0];
      2'b1?:
        _65_ = b[5:3];
      default:
        _65_ = a;
    endcase
  endfunction
  assign _27_ = _65_(3'hx, { 3'h0, _26_ }, { _23_, _19_ });
  function [1:0] _66_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _66_ = b[1:0];
      4'b??1?:
        _66_ = b[3:2];
      4'b?1??:
        _66_ = b[5:4];
      4'b1???:
        _66_ = b[7:6];
      default:
        _66_ = a;
    endcase
  endfunction
  assign _28_ = _66_(2'hx, { _22_, _20_, _29_, 2'h0 }, { _23_, _21_, _19_, _25_ });
  assign _29_ = _15_ ? 2'hx : 2'h3;
  assign _30_ = $signed(_16_) < 0 ? 1'h1 << - _16_ : 1'h1 >> _16_;
  assign _31_ = $signed(_16_) < 0 ? rx_sync << - _16_ : rx_sync >> _16_;
endmodule

module uart_tx(clk, rst_n, baud_tick, data_in, data_valid, tx_pin, busy);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input baud_tick;
  wire baud_tick;
  input [7:0] data_in;
  wire [7:0] data_in;
  input data_valid;
  wire data_valid;
  output tx_pin;
  reg tx_pin;
  output busy;
  reg busy;
  wire [31:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire [2:0] _13_;
  wire [2:0] _14_;
  wire _15_;
  wire [1:0] _16_;
  wire _17_;
  wire [1:0] _18_;
  wire _19_;
  wire [1:0] _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  reg [2:0] bit_idx;
  reg [7:0] data_buf;
  reg [1:0] state;
  assign _00_ = bit_idx + 32'd1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state <= 2'h0;
    else if (_06_) state <= _16_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) data_buf <= 8'h00;
    else if (_07_) data_buf <= data_in;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) tx_pin <= 1'h1;
    else if (_08_) tx_pin <= _22_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) bit_idx <= 3'h0;
    else if (_09_) bit_idx <= _14_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) busy <= 1'h0;
    else if (_10_) busy <= _21_;
  assign _01_ = { _12_, data_valid } != 2'h2;
  assign _02_ = { _15_, _11_ } != 2'h3;
  assign _03_ = | { _12_, _19_, _15_, _17_ };
  assign _04_ = { _12_, data_valid } != 2'h3;
  assign _05_ = | { _12_, _15_ };
  assign _06_ = & { baud_tick, _01_, _02_, _03_ };
  assign _07_ = & { _12_, data_valid, baud_tick };
  assign _08_ = & { baud_tick, _03_, _04_ };
  assign _09_ = & { baud_tick, _05_ };
  assign _10_ = & { _12_, baud_tick };
  assign _11_ = bit_idx < 32'd7;
  assign _13_ = _11_ ? _00_[2:0] : 3'h0;
  function [2:0] _43_;
    input [2:0] a;
    input [5:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _43_ = b[2:0];
      2'b1?:
        _43_ = b[5:3];
      default:
        _43_ = a;
    endcase
  endfunction
  assign _14_ = _43_(3'hx, { 3'h0, _13_ }, { _12_, _15_ });
  function [1:0] _44_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _44_ = b[1:0];
      4'b??1?:
        _44_ = b[3:2];
      4'b?1??:
        _44_ = b[5:4];
      4'b1???:
        _44_ = b[7:6];
      default:
        _44_ = a;
    endcase
  endfunction
  assign _16_ = _44_(2'hx, { _20_, 2'h2, _18_, 2'h0 }, { _12_, _19_, _15_, _17_ });
  assign _18_ = _11_ ? 2'hx : 2'h3;
  assign _20_ = data_valid ? 2'h1 : 2'hx;
  assign _21_ = data_valid ? 1'h1 : 1'h0;
  function [0:0] _48_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _48_ = b[0:0];
      4'b??1?:
        _48_ = b[1:1];
      4'b?1??:
        _48_ = b[2:2];
      4'b1???:
        _48_ = b[3:3];
      default:
        _48_ = a;
    endcase
  endfunction
  assign _22_ = _48_(1'hx, { _23_, 1'h0, _24_, 1'h1 }, { _12_, _19_, _15_, _17_ });
  assign _17_ = state == 2'h3;
  assign _15_ = state == 2'h2;
  assign _19_ = state == 2'h1;
  assign _23_ = data_valid ? 1'hx : 1'h1;
  assign _12_ = ! state;
  wire [7:0] _55_ = data_buf;
  assign _24_ = _55_[bit_idx +: 1];
endmodule
